### PR TITLE
47: removed console warnings

### PR DESCRIPTION
**Pull request by sebastianpiq**

### CODE REVIEW

**Comment by mpollingerQualabs** [comment]
Even though this is ok (code-wise), i believe we should not ship code with `console.log` statements.
There shouldn't be any `console.log` statements for debugging in production code. Also, if debugging, it's best practice to use the debugger instead of those statements.

**Comment by arrivillagaTomas** [comment]
I agree @mpollingerQualabs. 
What would be the path forward for the test files, where the console.log is currently used for reporting the outputs? Should we migrate to a testing framework such as Jest?

**Comment by mpollingerQualabs** [comment]
> I agree @mpollingerQualabs. What would be the path forward for the test files, where the console.log is currently used for reporting the outputs? Should we migrate to a testing framework such as Jest?

I think in the future we could consider something like Jest, for now it seems a little overkill (unless integrating it is effortless).
For the testing files, i don't really mind having the `console` statements there.

**Comment by arrivillagaTomas** [comment]
So the path forward would be to keep this functionality, and to disable the lint flag for this on the test files?

**Comment by mpollingerQualabs** [comment]
> So the path forward would be to keep this functionality, and to disable the lint flag for this on the test files?

Unless there's some opposition, i would say yes.

**Review by mpollingerQualabs — APPROVED** [review]

**Review by arrivillagaTomas — APPROVED** [review]

**Review by CamiloBorba09 — APPROVED** [review]

**Review by rodrigo-mira — APPROVED** [review]

**Pull request merged**
